### ISSUE TITLE
What should the return types of Lexeme::end() and Lexeme::len() be?

### ISSUE THREAD

**Issue by ltratt** [softdevteam/grmtools#106]
Currently these two functions have return types `Option<usize>` where `None` means "this lexeme was inserted by error recovery". In a sense this seems like the right thing to do, in that it stops users accidentally thinking they've got a "normal" lexeme. But in practise I'm starting to be less sure about it because it seems that I always end up doing `l.end().unwrap_or_else(|| l.start())`.

Indeed, if I look in lrlex/lrpar I always end up doing that:

```
$ rg end\\\(\\\) lrlex lrpar
lrlex/src/main.rs
74:            &input[l.start()..l.end().unwrap_or_else(|| l.start())]

lrlex/src/lib/lexer.rs
203:                    let len = m.end();
294:        &self.s[st..l.end().unwrap_or(st)]

lrlex/src/lib/parser.rs
113:        let line = self.src[i..i + line_len].trim_end();
141:        let re_str = line[..rspace].trim_end().to_string();

lrpar/src/lib/parser.rs
61:                    let lt = &input[lexeme.start()..lexeme.end().unwrap_or_else(|| lexeme.start())];
322:                    span.push(la_lexeme.end().unwrap_or_else(|| la_lexeme.start()));
444:                            span_uw.push(la_lexeme.end().unwrap_or_else(|| la_lexeme.start()));
976:                    let len = m.end();

lrpar/examples/calc_parsetree/src/main.rs
89:                        self.s[lexeme.start()..lexeme.end().unwrap_or_else(|| lexeme.start())]
```

This is making me wonder if we've been too precise for our own good. But I'm really not sure: I really can see people shooting themselves in the foot if they've forgotten that some tokens can be inserted as the result of error recover. Thoughts are appreciated!

**Comment by ltratt** [comment]
Should have been clear that I'm asking @ptersilie for thoughts.

**Comment by ptersilie** [comment]
Does `l.end().unwrap_or_else(|| l.start())` just return `l.start()`, which then makes `&input[` return an empty string?

Maybe we can add a method `l.was_inserted_by_error_recovery()` that allows users to easily check if a lexeme is real or not. Or we add a function `l.get_from_input(&input)`, which returns `""` if the lexeme was inserted by error recovery, and then tell users to use that instead of indexing the input themselves?

**Comment by ltratt** [comment]
The `inserted` function allows you to tell if a lexeme was inserted by error recovery or not. My worry is that people will forget to test for that, then they'll do something like `lexeme.end()` and be surprised that they end up with a zero length lexeme (for a lexeme definition that seemingly could never be zero length). I'm just not sure if I'm being unduly paranoid or not.

**Comment by ptersilie** [comment]
I think we can't reasonably worry about everything the user might forget, especially if that means we make the life of less forgetful users more difficult by forcing them to use workarounds like `l.end().unwrap_or_else(|| l.start())`. I rather have `end/start` return 0 if the lexeme was inserted. I'm sure users will quickly remember that these are inserted lexemes when they get zero length ones.

**Comment by ltratt** [comment]
OK, I'll raise a PR.
