### ISSUE TITLE
Support to work with subgrammars

### ISSUE THREAD

**Issue by superriva** [softdevteam/grmtools#110]
Let I have subgrammars:

`<subgrammar1>` with rules `"1","2","+"`  
`<subgrammar2>` with rules `"3","4","-"`     

And I have `<input file>` 
```
1+2;
3-4;
```
Then I have to get 
`<grammar>` = `<subgrammar1>` + `<subgrammar2>` to parse all lines of `<input file>`.

What paths exist? 
Thank you.
// I hope my question is more clear now.

**Comment by ltratt** [comment]
I'm sorry -- I don't understand the question. Can you perhaps try rephrasing?

**Comment by ltratt** [comment]
I think I now see what you're asking.

Grammar composition isn't currently supported in grmtools (or, indeed, in Yacc) and probably never will be. It's a *really* hard topic: at a bare minimum, it opens up issues of ambiguity (but it also raises issues about how to lex etc.). This is an active research area (see e.g. [my (old) high level overview](https://tratt.net/laurie/blog/entries/parsing_the_solved_problem_that_isnt.html); or, for more technical meat, [this](http://soft-dev.org/pubs/pdf/vasudevan_tratt__detecting_ambiguity_in_programming_language_grammars.pdf) or [this](https://soft-dev.org/pubs/html/diekmann_tratt__eco_a_language_composition_editor/) or even [this](http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.56.883&rep=rep1&type=pdf) for some clues as to some of the problems).

Looked at another way, if you want to do batch parsing (which is what grmtools offers), you probably just want to combine subgrammar1 and subgrammar2 manually and deal with things that way.
