### ISSUE TITLE
Allow qualifying types (module::Foo) in parser files

### ISSUE THREAD

**Issue by pablosichert** [softdevteam/grmtools#127]
It would be nice if it was allowed to qualify types in parser files.

E.g. being able to write a production:

```rust
Integer -> context::Result<i32>:
  [...]
;
```

Currently, using `::` yields an error:

```
Illegal string at line [...] column 20
```

---

The context was included in the `.y` file as

```rust
use crate::parser::context::*;
```

and contains

```rust
pub trait Error = std::error::Error;
pub type Result<T> = std::result::Result<T, Box<dyn Error>>;

[...]
```

**Comment by ltratt** [comment]
That's a definite oversight. Will fix.
