### ISSUE TITLE
Fully qualify structs in generated code to avoid name conflicts

### ISSUE THREAD

**Issue by pablosichert** [softdevteam/grmtools#128]
If you include some custom types in the context of a parser file, specifically

```rust
struct Result {}
```

it will change the meaning of `Result` aka. `::std::result::Result` in the generated code.

If the generated code fully qualified (`::some::path::to::Struct`) the usage of all structs, no such name conflicts would be possible.

**Comment by ltratt** [comment]
Agreed. I'll look into this. At the moment the way Rust source is generated is a horrible hack, with no guarantees of hygiene. But, that said, fully qualified names will definitely reduce the chances of clashes.
