### ISSUE TITLE
Support file paths in process_file_in_src / lrlex_mod! / lrpar_mod!

### ISSUE THREAD

**Issue by pablosichert** [softdevteam/grmtools#132]
It would be nice if the path specified in `process_file_in_src` would be replicated over to `$OUT_DIR` and `lrlex_mod!`/`lrpar_mod!` would support strings instead of identifiers.

That way, the usage of

```rust
.process_file_in_src("some/path/to/file.y")
```

and

```rust
lrpar_mod!("some/path/to/file.y");
```

would be symmetric.

It would also have the benefit of not creating conflicts for `.process_file_in_src("a/file.y")` and `.process_file_in_src("b/file.y")`.

**Comment by ltratt** [comment]
I think this might be a good idea. Let me look into it.

**Comment by pablosichert** [comment]
That was quick! Super cool.
