### ISSUE TITLE
Add `rust,noplaypen` to example grammar code in the documentation

### ISSUE THREAD

**Issue by rljacobson** [softdevteam/grmtools#160]
Much of the example code in the documentation is not syntax highlighted, presumably because it is a mix of both Rust and `lrpar` syntax rather than pure Rust. However, highlighting it as Rust code seems to work quite well. Also, the failure mode of Highlight.js is quite benign: in the worst case, a few tokens are left the default text color (black/dark gray). 

The playpen feature (the ▶️ button) doesn't make much sense on those code blocks, as the code will not compile on https://play.rust-lang.org/. The `noplaypen` annotation turns this off.

Here's an example:

    ```rust,noplaypen
	Assign -> ASTAssign: "ID" "+" Expr
	{
        let id = $lexer.span_str($1.as_ref().unwrap().span()).to_string();
	    ASTAssign::new(id, $3)
	}

	%%

	struct ASTAssign {
	    id: String
	}

	impl ASTAssign {
	    fn new(name: String) -> Self {
	        ASTAssign { name }
	    }
	}
    ```

<img width="508" alt="Screen Shot 2020-02-23 at 3 25 10 PM" src="https://user-images.githubusercontent.com/1412598/75119418-be66c500-5650-11ea-8648-11d2d263343d.png">

I've already done this for the grmtools parsing idioms page but thought I'd ask if this PR would be welcome before I do the rest of the docs.

**Comment by ltratt** [comment]
Sorry, I had somehow not noticed that this issue had been raised -- mea culpa! I agree that highlighting things with Rust syntax highlighting is a good idea, and that `noplaypen` makes sense. I'd certainly welcome a PR that did that.
