### ISSUE TITLE
Lexer start conditions (state) similar to flex

### ISSUE THREAD

**Issue by alekratz** [softdevteam/grmtools#215]
GNU flex provides the option to have "start conditions" for the lexer, allowing the lexer to ignore certain rules when getting the next token. It's a nice feature to have, are there any plans to implement it?

see this link for what I'm talking about: https://www.cs.virginia.edu/~cr4bd/flex-manual/Start-Conditions.html

**Comment by ltratt** [comment]
I have no plans to add this to lrlex myself (I've never used this functionality), but I would welcome a PR which did it!

**Comment by alekratz** [comment]
I will keep that in mind, then. I'm not planning on implementing it right now but maybe in the future if it hasn't been already and I find myself wanting it.

**Comment by ltratt** [comment]
Sounds like a plan! I'll close this for now, but feel free to reopen if and when this becomes interesting to you again!
