### ISSUE TITLE
Allow generating `pub mod` instead of just `mod`

### ISSUE THREAD

**Issue by FranklinChen** [softdevteam/grmtools#222]
I noticed when wanting to pull out `lrlex_mod!` and `lrpar_mod!` calls that they unfortunately generate `mod` instead of `pub mod`. Could the macro be modified to optionally allow generation of `pub`?

**Comment by FranklinChen** [comment]
I'm using a workaround right now so it's not critical, but it might be nice to not have to do this:

```
lrlex_mod!("chat.l");
lrpar_mod!("chat.y");

pub mod chat_lexer {
    pub use crate::chat_l::*;
}

pub mod chat_parser {
    pub use crate::chat_y::*;
}
```

**Comment by ltratt** [comment]
You should be able to use https://docs.rs/lrpar/0.9.1/lrpar/struct.CTParserBuilder.html#method.visibility and https://docs.rs/lrlex/0.9.1/lrlex/struct.LexerBuilder.html#method.visibility -- let me know if those don't work for you and I'll have a further look.

**Comment by FranklinChen** [comment]
D'oh, I should have looked up the builder docs. OK, `lrpar` works but in `lrlex` `Visibility` is not exported.

**Comment by ltratt** [comment]
Oops, yes, that is definitely a bug in lrlex!

**Comment by ltratt** [comment]
Hopefully https://github.com/softdevteam/grmtools/pull/223 fixes this problem!

**Comment by FranklinChen** [comment]
Hmm, actually, the `lrpar` setting of visibility doesn't seem to have an effect.

**Comment by ltratt** [comment]
Looking at the code in `ctbuilder.rs` it looks like it should:

```rust
    fn output_file<P: AsRef<Path>>(
        &self,
        grm: &YaccGrammar<StorageT>,
        stable: &StateTable<StorageT>,
        mod_name: &str,
        outp_rs: P,
        cache: &str,
    ) -> Result<(), Box<dyn Error>> {
        let mut outs = String::new();
        outs.push_str(&format!(
            "{} mod {} {{\n",
            self.visibility.cow_str(),
            mod_name
        ));
        outs.push_str(
            "    #![allow(clippy::type_complexity)]
",
        );
```

It might be worth checking that you're generating a new file appropriately, because you could hit some fun things (e.g. ntp) that mess with rebuilding. When I'm in doubt I `rm` the `target` directory completely, just to be rule that out.

**Comment by FranklinChen** [comment]
Yeah, I had to delete `target`.

**Comment by ltratt** [comment]
OK, looking at it, lrpar isn't recording visibility in its rebuild cache, so I was slandering ntp incorrectly! Another PR coming.

**Comment by ltratt** [comment]
v0.9.2 of the libraries are now on crates.io and should fix the issues above. Thanks for reporting them!
