### ISSUE TITLE
Token ids are not accessible

### ISSUE THREAD

**Issue by rbartlensky** [softdevteam/grmtools#23]
For the [calculator grammar](https://github.com/softdevteam/grmtools/blob/master/lrpar/examples/calcparse/src/calc.y), the following two files are generated:

``` rust
///  calc_l.rs
mod calc_l {use lrlex::{LexerDef, Rule};

pub fn lexerdef() -> LexerDef<u8> {
    // code not shown for the sake of brevity 
} // fn ends here!!!
...
#[allow(dead_code)]
const T_INT: u8 = 4;
...
} // mod ends here!!!
```
``` rust
///  calc_y.rs
mod calc_y {use lrpar::{Lexeme, Node, parse_rcvry, ParseError, reconstitute, RecoveryKind};

pub fn parse(lexemes: &[Lexeme<u8>])
          -> Result<Node<u8>, (Option<Node<u8>>, Vec<ParseError<u8>>)> { 
    // code not shown for the sake of brevity 
} // fn ends here!!!
} // mod ends here!!!
...
#[allow(dead_code)]
const R_TERM: u8 = 2;
...
```

One can match `Node::NonTerm`s as shown [here](https://github.com/softdevteam/grmtools/blob/master/lrpar/examples/calcparse/src/main.rs#L75). `R_TERM` can be used because it is included [here](https://github.com/softdevteam/grmtools/blob/master/lrpar/examples/calcparse/src/main.rs#L15), and because it is not part of the `calc_y` module. If the user wanted to match a `Node::Term` based on a token id, they wouldn't be able to do the following:
``` rust
match node {
    // does not compile as T_INT does not exist in the current scope
    // and it is a private constant in the `calc_l` module
    Term{lexeme} if lexeme.tok_id() == T_INT => {
        println!("hello");
     },
     _ => unreachable!();
}
```

Let me know if I am missing something obvious. If I am correct, then simply moving [this](https://github.com/softdevteam/grmtools/blob/master/lrlex/src/lib/builder.rs#L204) statement to line 190 would solve the issue.

**Comment by ltratt** [comment]
Mea culpa! There is definitely a problem here, although, IMHO, the right fix is a bit different. The first problem is that `R_IDX` and so on *should* be part of the `calc_y` module and accessed by `calc_y::R_IDX`. However, `T_IDX` and friends are currently private so although we should be able to use `calc_l::T_INT` we currently can't. Fix coming shortly.
