### ISSUE TITLE
From repair sequence to repaired input strings

### ISSUE THREAD

**Issue by josepablocam** [softdevteam/grmtools#279]
This may not be the right venue to ask, but I thought it was worth while asking (since couldn't find in README/docs).

Is there an API provided to apply the repair sequence(s) produced to the original input (i.e. producing a new input string that would not raise a parse error)? Or is the expectation that consumers do that themselves? Since users can plug in custom lexers, I'm inclined to believe that the latter is the expectation, but I wanted to confirm before reimplementing something already available in `grmtools`.

**Comment by ltratt** [comment]
If you have further questions, please shout, otherwise I think this can probably be closed.

**Comment by josepablocam** [comment]
This was really helpful, thank you so much!

**Comment by bendrissou** [comment]
Hi @josepablocam 

I have the same question. It would be great if you can share your solution here.
