### ISSUE TITLE
Break `>>` into `>` and `>`

### ISSUE THREAD

**Issue by romdotdog** [softdevteam/grmtools#301]
Hi! Sorry if this is a loose fit for an issue, but I'd love to get CPCT+ going in my language.

I've been (rather fruitlessly) trying to implement generics in my language, but I ran into this issue; after lots of googling I could not seem to figure it out. lrlex parses `>>` into a right bit shift, so I'm having trouble writing logic for nested generics in yacc form.

```
Array<Array<T>>
             ^^ lexer thinks this is a bit shift instead of two greater thans
```

Does anyone have any ideas that will play nicely with CPCT+? Or is the only way to write a custom lexer to fool the parser (if that's even possible)?

**Comment by romdotdog** [comment]
Ah, as always, I find a solution right after posting an issue.
I defined this in my lexer:
```
> ">"
\s+> "W>"
```
and defined a rule:
```rs
Gt -> Span:
    ">" { $span } | 
    "W>" { $span };
```
and now my bit shift production looks like:
```rs
ShiftExpr Gt ">" TermExpr { Expr::Binary(BinOp::Shr, Box::new($1), Box::new($4)) } |
```
I'm still wondering if there are any other less hacky solutions however?

**Comment by romdotdog** [comment]
After extensive reading, I don't think there is, so I'll close this issue.

**Comment by ltratt** [comment]
This isn't anything to do with lrlex per se -- it's about bracket overload in common programming language syntax. If you want to write a custom lexer, you can fully solve this, but in lrlex and friends a typical solution is to *only* define `> ">"` in your lexer and then `ShiftExpr: ">" ">"` in your grammar. This does allow people to write `> >` for bit shift, but that's generally considered acceptable.
