### ISSUE TITLE
how to use “ and space with .l file

### ISSUE THREAD

**Issue by RickSKy** [softdevteam/grmtools#359]
I have tried some example， but all compile failed.It is not same with flex
```rust
%%
# [0-9]+ \"      "TEST"
```
```rust
%%
#\ [0-9]+\ \"      "TEST"
```
and i write with flex before, it compile success with c code:
```flex
testline  #\ [0-9]+\ \"
%%
testline   return TEST;
```
I found that this project not support define testline before, and with " or "return  XXX;"  will compile failed

**Comment by ratmice** [comment]
I tested this out on both the release, where it indeed does fail, and the current master branch where everything seemed to work.  
I believe that this was fixed already in one of https://github.com/softdevteam/grmtools/pull/333 or https://github.com/softdevteam/grmtools/pull/335

Could you try with the master branch?

**Comment by RickSKy** [comment]
Thanks. 
Edit2 has resolve the problem.
Edit: testline just like a var or symbol, flex will replace  testline with #\ [0-9]+\ \" in %%; it can improve the readable for the code

**Comment by ltratt** [comment]
Thanks @ratmice for testing and thanks for the report @RickSKy. We're hoping to make a release soon-ish so that these fixes can be widely used!

**Comment by RickSKy** [comment]
the question in Edit is not solved now.
"testline just like a var or symbol, flex will replace testline with #\ [0-9]+\ " in %%; it can improve the readable for the code."
that means:
1. support alias or var define in lrlex
2. replace alias or var define's real value when compiling for .l file
