### ISSUE TITLE
write .l with var for lrlex

### ISSUE THREAD

**Issue by RickSKy** [softdevteam/grmtools#361]
when we use flex, we can write .l like that:
```
testline  #\ [0-9]+\ \"
%%
{testline}   return TEST;
```
testline just like a var or symbol. And flex will replace testline with #\ [0-9]+\ " in %% when compiling; it can improve the readable for the .l file when the regex is complex.
It will be nice to write .l with var for lrlex.

**Comment by ltratt** [comment]
I'm not adverse to having a PR with such a feature, but I can't see that flex uses the term "testline"?
