### ISSUE TITLE
Broken links for YACC and LEX Manual in grmtools-book

### ISSUE THREAD

**Issue by madhavpcm** [softdevteam/grmtools#374]
The resource intended to be used in the guides are down. 

http://dinosaur.compilertools.net/lex/index.html and

http://dinosaur.compilertools.net/yacc/index.html

**Comment by ltratt** [comment]
Is this a temporary or permanent issue?

**Comment by madhavpcm** [comment]
> Is this a temporary or permanent issue?

Temporary, can be easily fixed by a newer resource or an alternative?

**Comment by ltratt** [comment]
PR happily accepted!

**Comment by madhavpcm** [comment]
> PR happily accepted!

Well I'm not sure what guide is the best from grmtools' perspective, however I'll see if something fits. Thanks

**Comment by ltratt** [comment]
If all else fails, an archive.org link might be OK.
