### ISSUE TITLE
%ignore like in flex

### ISSUE THREAD

**Issue by madhavpcm** [softdevteam/grmtools#376]
Flex uses %ignore to ignore the patterns matching with given regex.

Something like :
`
%ignore <regex>
`

Im not sure but, this doesnt work in lrlex, or is there any alternative which I failed to find?

**Comment by ltratt** [comment]
lrlex does this slightly differently: you define a normal rule but instead of using quotes for the identifier (`"blah"`) you use just a semi-colon. Commonly this is used to match and "throw away" whitespace:

```
[\t ]+ ;
```

Is that what you're looking for?

**Comment by madhavpcm** [comment]
%%
L\d+:\n "LABEL"
.* ;
[\t\n ]+ ;

I want to detect labels in an assembly language, I tried this earlier, however labels are not matching,

**Comment by ltratt** [comment]
The regex might or might not be doing what you hope for. lrlex does have a basic debugging binary: `cargo run --bin lrlex <lex.l> <file>` will print out the lexemes that are matched. I find this useful to debug lex files.

**Comment by madhavpcm** [comment]
> The regex might or might not be doing what you hope for. lrlex does have a basic debugging binary: `cargo run --bin lrlex <lex.l> <file>` will print out the lexemes that are matched. I find this useful to debug lex files.

I was using the lrlex binary which I cargo installed globally. It gives a blank output, so Not sure why text like L0: or L1: is not matching.

**Comment by ltratt** [comment]
Ah, you're hitting the "longest match" behaviour in lex. In essence `.*` is matching all your input, "winning" because it matches more text then any other rule, and then `;` is throwing it away. For example this lex file:

```
%%
L\d+:\n "LABEL"
[\t\n ]+ ;
```

matches labels correctly:

`
$ cat /tmp/t
L0:
L1:

$ cargo run --bin lrlex /tmp/t.l /tmp/t
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/lrlex /tmp/t.l /tmp/t`
LABEL L0:

LABEL L1:

```

**Comment by madhavpcm** [comment]
> Ah, you're hitting the "longest match" behaviour in lex. In essence `.*` is matching all your input, "winning" because it matches more text then any other rule, and then `;` is throwing it away. For example this lex file:
> 
> ```
> %%
> L\d+:\n "LABEL"
> [\t\n ]+ ;
> ```
> 
> matches labels correctly:
> 
> ```
> $ cat /tmp/t
> L0:
> L1:
> 
> $ cargo run --bin lrlex /tmp/t.l /tmp/t
>     Finished dev [unoptimized + debuginfo] target(s) in 0.05s
>      Running `target/debug/lrlex /tmp/t.l /tmp/t`
> LABEL L0:
> 
> LABEL L1:
> ```

is there any way to ignore other tokens of the assembly language, other than manually matching and ignoring ? l

**Comment by ltratt** [comment]
> is there any way to ignore other tokens of the assembly language, other than manually matching and ignoring ?

You can probably do this if you make the *last* rule of the lex file:

```
. ;
```

Make sure it's the *last* rule, or you'll get odd behaviour if there are other single-character lexemes.

**Comment by madhavpcm** [comment]
> > is there any way to ignore other tokens of the assembly language, other than manually matching and ignoring ?
> 
> You can probably do this if you make the _last_ rule of the lex file:
> 
> ```
> . ;
> ```
> 
> Make sure it's the _last_ rule, or you'll get odd behaviour if there are other single-character lexemes.

Thanks this works
