### ISSUE TITLE
Bug in grmtools documentation - traits not displaying required method names

### ISSUE THREAD

**Issue by Benjscho** [softdevteam/grmtools#396]
Appears to be a bug in the hosted grmtools documentation where trait method names aren't displayed in either the code sample or the trait page - see screenshot below of [documentation at this link](https://softdevteam.github.io/grmtools/master/api/lrpar/trait.Lexeme.html). This was noticed in Firefox on Windows, and loading the page from the Edge browser I saw the same issue. 

I built the documentation myself using `cargo doc`, and the pages appear to be working fine when locally built. I can't see anything in the source or settings that would be causing this, so maybe it's a hosting issue or some artifact of the build process? 

![image](https://user-images.githubusercontent.com/47790940/219979534-e52514c1-3ea5-4c62-8732-1da0493beb8b.png)

**Comment by Benjscho** [comment]
Looking a little further, this appears to only be affecting the `lrpar` crate for the `master` release, not latest.

**Comment by ltratt** [comment]
I see the same. Lord alone knows what's caused that! I'll try causing a doc rebuild and see if it fixes it.

**Comment by ltratt** [comment]
That didn't fix it. @ratmice I don't suppose you have any ideas? If not, I'll do an in-depth investigation tomorrow.

**Comment by Benjscho** [comment]
Could it be an issue with rust doc nightly versions? Looking at the doc pages it looks like `master` is being built with `rustdoc 1.69.0-nightly (4507fdaaa 2023-02-18)` but `latest` is using` rust doc 1.69.0-nightly (d7948c843 2023-01-26)`. The master docs are also missing the rust doc toolbar at the top. Maybe pinning rust doc would fix it

**Comment by Benjscho** [comment]
Also sorry I'm a little unclear on how `latest` and `master` differ/what they both build from

**Comment by ltratt** [comment]
"Latest release" is 0.13.1 (at the moment!); "master" is the tip of the github repo. In general, you probably want "latest release".

[I still think the "master" documentation shouldn't be broken, as people do read it. But I've not got any obvious ideas for fixing it right now!]

**Comment by ratmice** [comment]
I can reproduce it locally using `RUSTDOCFLAGS="-Dwarnings" cargo +nightly doc --no-deps` which adds the +nightly flag to the command line used in .buildbot.sh`. While everything works fine without the `+nightly`.

**Comment by ltratt** [comment]
@ratmice You're a genius -- I was looking in the wrong place until you pointed out this is "nightly" related. I'll do the fix now; it'll take someone until tomorrow to review it (we have a post-PR snare script that uploads the docs to github which, embarrassingly, I'd completely forgotten about). With luck this will be fixed in about 12 hours from now!

**Comment by Benjscho** [comment]
Ace, thank you!

**Comment by ratmice** [comment]
Actually Ben was the first to point out nightly, credit where credit is due!

**Comment by ltratt** [comment]
Mea culpa! Let's say the one safe thing is that I made several mistakes :p

**Comment by ltratt** [comment]
And fixed -- thanks both for pointing this out and bearing with me while I wrapped my head around what the issue was!
