### ISSUE TITLE
Request for example of handling string literals in lexer

### ISSUE THREAD

**Issue by yuanweixin** [softdevteam/grmtools#398]
I am having trouble figuring out how to handle string literals in the lexer. 

By string literals I mean: 
* a character sequence starting with a double quote and ending with a double quote
* escape sequences may occur inside the literal. for example, the sequence \\ " (slash, double quote) represents a double quote literal inside the string, and should not be interpreted as the end marker of the string. 
* char literal sequences e.g. \xyz where x,y,z are some numeric digit can be processed into the actual character. 

I see there is support for start conditions so I can denote an exclusive string state, but not sure if there is a way to "build up" the string literal and handle the escape characters while in that state. 

Tips/pointers would be much appreciated! But ideally this would be added as an example.

**Comment by ltratt** [comment]
The precise rule you'll want is context dependent but here are a couple of possibly similar-ish examples:

* https://github.com/softdevteam/yksom/blob/master/src/lib/compiler/som.l#L20
* https://github.com/ltratt/pizauth/blob/master/src/config.l#L4

**Comment by yuanweixin** [comment]
Thanks. I think with the current design I can handle the string literals in the parser actions instead.
