### ISSUE TITLE
Online Yacc/Lex editor/tester

### ISSUE THREAD

**Issue by mingodad** [softdevteam/grmtools#422]
Would be nice if this project could also have something like https://mingodad.github.io/parsertl-playground/playground/ (repository here https://github.com/mingodad/parsertl-playground) to allow edit/debug/test `Yacc/Lex` grammars online.

Any feed back is welcome !

**Comment by ltratt** [comment]
If someone wanted to create such a thing, we'd happily link to it, but I doubt I'll find the time myself I'm afraid.

**Comment by mingodad** [comment]
Have you already looked at it ?

**Comment by ltratt** [comment]
It looks cool. Like I said, it'll take someone other than me to do this I'm afraid.

**Comment by ratmice** [comment]
Like I said in #385, I have always been planning on porting nimbleparse_lsp to wasm, and making a playground version available.
I have at least made various attempts locally but nothing has panned out. If anyone has more rust-wasm and editor-wasm interface familiarity or just wants to help in that regard I would be very grateful, the specific issue for that work is https://github.com/ratmice/nimbleparse_lsp/issues/6 (I should probably leave what I have tried/gotten stuck on in that linked issue).  It may be worthwhile looking at other web based editors than vscode which support LSP and see if  any others are easier to undertake an initial port on.  I haven't actually seen any vscode web-extensions running rust compiled wasm code, so (afaik) there is little in the way of prior art to reference on that undertaking.

Anyhow that is still my plan/focus regarding this issue.

**Comment by ltratt** [comment]
Thanks @ratmice!
