### ISSUE TITLE
Docs Question - Optional Prefix to Regular Expressions

### ISSUE THREAD

**Issue by DavidHVernon** [softdevteam/grmtools#438]
Snip from [https://softdevteam.github.io/grmtools/latest_release/book/lexcompatibility.html](https://softdevteam.github.io/grmtools/latest_release/book/lexcompatibility.html)

> Both Lex and grmtools lex files support start conditions as an optional prefix to regular expressions, listing necessary states for the input expression to be considered for matching against the input. Lex uses a special action expression BEGIN(state) to switch to the named state. grmtools lex files use a token name prefix.

Could someone point me at an example of this? I'm very curious, and think it might fix an issue that i've been wrestling with.

**Comment by ratmice** [comment]
The example in the repo that uses this is the `lrpar/examples/start_states`:

https://github.com/softdevteam/grmtools/blob/master/lrpar/examples/start_states/src/comment.l

When the left hand side, before the regex matches the current state, the token can be matches,
and the right hand-side transitions to a new state when the token has matched.

**Comment by DavidHVernon** [comment]
Thank you for the clarification. I'm not quite sure that I follow, but I will give it some more thought before I ask follow-on questions.

**Comment by ratmice** [comment]
I tried to update that hopefully making it a bit clearer.

**Comment by DavidHVernon** [comment]
Thank you for that, but the real issue is that I was reading it in the grocery store checkout line :)

**Comment by DavidHVernon** [comment]
Hey all. Thanks for the help here. Life has gotten in between me and Rust lately, but I've got my head around this now and I suppose we can close the issue.
