### ISSUE TITLE
lrpar:%prec not followed by token name

### ISSUE THREAD

**Issue by liluyue** [softdevteam/grmtools#450]
I use **%nonassoc**,always error
<img width="1179" alt="截屏2024-05-13 14 48 55" src="https://github.com/softdevteam/grmtools/assets/19216288/1ccea5d7-a5eb-4e65-80c9-9202ddbd8846">

**Comment by ltratt** [comment]
If you can include the raw text of the input and the error that's produced, that would be helpful.

**Comment by liluyue** [comment]
> If you can include the raw text of the input and the error that's produced, that would be helpful.
Priority added to the example:
```
%start Expr
%left '+' '-'
%left '*' '/'
%nonassoc 'u'
%%
Expr -> Result<u64, ()>:
      Expr '+' Expr { Ok($1? + $3?) }
    | Expr '-' Expr { Ok($1? - $3?) }
    |  Expr '*' Expr { Ok($1? * $3?) }
    | Expr '/' Expr { Ok($1? / $3?) }
    | Factor { $1 }
    | '-' Factor %prec 'u' { Ok(-$2?) }
    ;


Factor -> Result<u64, ()>:
      '(' Expr ')' { $2 }
    | 'INT'
      {
          let v = $1.map_err(|_| ())?;
          parse_int($lexer.span_str(v.span()))
      }
    ;
%%
// Any functions here are in scope for all the grammar actions above.

fn parse_int(s: &str) -> Result<u64, ()> {
    match s.parse::<u64>() {
        Ok(val) => Ok(val),
        Err(_) => {
            eprintln!("{} cannot be represented as a u64", s);
            Err(())
        }
    }
}

```

**Comment by ltratt** [comment]
Can you also include the error you're seeing please?

**Comment by liluyue** [comment]
```
[Error] in src/calc.y
    12|     | '-' Factor %prec 'u' { Ok(-$2?) }
                                %prec not followed by token name
    
    11|     | Factor { $1 }
              ^^^^^^ Unknown reference to rule 'Factor'
    
```

**Comment by ltratt** [comment]
That *probably* means that your lexer isn't defining `u` is a token type? [It could be a bug in cfgrammar of course, but it has a check `if self.ast.tokens.contains(&sym)` that looks sensible to me, at least at first glance.]

**Comment by liluyue** [comment]
It can be troublesome to resolve the shift/reduce between rules without **%nonassoc“. According to yacc's rules,**% nonassoc** should not be bound to a token

**Comment by ltratt** [comment]
I don't think `%nonassoc` is relevant to the error you're seeing but @ratmice might have a better idea than me.

**Comment by ratmice** [comment]
To get the example working through nimbleparse (besides adding a lex file for it), I had to add a 
```
%token 'u'
%expect-unused 'u'
```

as well as using the `Unmatched` trick from https://softdevteam.github.io/grmtools/master/book/errorrecovery.html in the lexer.  Which seemed to work.

**Comment by ltratt** [comment]
I think there's at laest 1 bug in grmtools here. Investigating.

**Comment by ltratt** [comment]
I'm going to keep this one open until #453 is reviewed, because I'm not 100% confident of my fix!
