### ISSUE TITLE
Is there a way to pass Conext in `$lexer` when doing action?

### ISSUE THREAD

**Issue by Taylor-lagrange** [softdevteam/grmtools#454]
In my syntax parsing scenario, I need some external information to explain the current AST. It would be very convenient if I could acces/modify a context in `$lexer` during action, but after looking through the documentation, there seems to be no way to do this.

Case like I wanna do:

```yacc
duration -> Result<Duration, String>:
       DURATION {
               let ctx = $lexer.get_context();
               parse_duration($lexer.span_str($span), ctx.get_attr("step")) 
       }
;
```

Generally to hope `lexer` has the ability to store context, Is there any way to do this?

**Comment by ltratt** [comment]
Does https://softdevteam.github.io/grmtools/master/book/actioncode.html#additional-parse-parameter help?

**Comment by Taylor-lagrange** [comment]
That is very helpful! Thank you, I am new to grmtools.

**Comment by ltratt** [comment]
Best of luck! I'll close this for now but feel free to reopen if this feature isn't sufficient.
