### ISSUE TITLE
Errors in catching incorrectly terminated productions

### ISSUE THREAD

**Issue by bendrissou** [softdevteam/grmtools#463]
Hi,

After the last [merge](https://github.com/softdevteam/grmtools/pull/460), some of my projects are failing to build.

```
error: failed to run custom build command for `lua_repair v0.1.0 (/home/AFLplusplus/custom_mutators/rust/lua_repair)`

Caused by:
  process didn't exit successfully: `/home/AFLplusplus/custom_mutators/rust/target/release/build/lua_repair-162ad1ab4214539c/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at lua_repair/build.rs:14:10:
  called `Result::unwrap()` on an `Err` value: 
  	Production not terminated correctly at line 73 column 5
  	Unknown reference to rule 'retstatopt' at line 65 column 19
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

I don't think I have any grammar rules of the form:
```
R: A {B} C;
```

But I do have rules like:

```
R: A {B} 
 | {C};
```

Do you think that is an incorrectly terminated productions?
 
Thank you.

**Comment by ltratt** [comment]
@bendrissou Can you send me a complete grammar that shows this problem please? I may well have made a mistake!

**Comment by ltratt** [comment]
I can confirm that this is due to a mistake on my part -- thanks for reporting!

**Comment by ltratt** [comment]
@bendrissou This should now be fixed.

**Comment by bendrissou** [comment]
Thank you for the prompt fix. Things are looking good now.
