### ISSUE TITLE
Give the parser a variable

### ISSUE THREAD

**Issue by Lurgrid** [softdevteam/grmtools#469]
Hello,

I have a small question: is it possible to send data (such as a parameter to ``parse()``) to the parser so that it can be accessed in the “Yacc” file? After reading the documentation and the book, I don't see any way of doing this “cleanly”. You could use a static variable, but that wouldn't be thread-safe.

If this really isn't possible right now, it might be a good idea to add it, as it would open up a whole new range of possibilities.

**Comment by ratmice** [comment]
It sounds like the `%parse-param` directive is what you are looking for, if the data you want to pass is `Copy`.

* in the book [book](https://softdevteam.github.io/grmtools/master/book/actioncode.html#additional-parse-parameter)
* additional param to [parse()](https://docs.rs/lrpar/latest/lrpar/struct.CTParserBuilder.html#method.build) is documented here

**Comment by Lurgrid** [comment]
I think I'm blind, I didn't see it.

Sorry to have bothered you for nothing
