### ISSUE TITLE
Ignoring `$X` within strings for actions

### ISSUE THREAD

**Issue by ptersilie** [softdevteam/grmtools#59]
When translating action code we currently replace all `$X` within it to reference the correct value from the actions stack. However, since we are using a simple regex to do this, we also replace any occurrence of `$[0-9]+` within comments and strings. While we can live with altering comments, changing strings may prevent users from generating reasonable programs.

Since parsing rust is too big a task, a quick solution to this problem would be to count unescaped quotes, and only replace occurrences of `$X`, if the count is equal. This should at least get rid of replacements within user strings.

**Comment by ltratt** [comment]
Fixed in #144.
